import type { Specialist } from "./types";

export const specialists: Specialist[] = [
  {
    id: "1",
    name: "John Doe",
    specialization: "Cardiologist",
    experience: "10 years",
    issues: ["Heart Attack", "Stroke", "Hypertension"],
    rating: 4.5,
  },
  {
    id: "2",
    name: "Jane Smith",
    specialization: "Oncologist",
    experience: "15 years",
    issues: ["Cancer"],
    rating: 4.8,
  },
  {
    id: "3",
    name: "Michael Johnson",
    specialization: "Psychiatrist",
    experience: "8 years",
    issues: ["Depression", "Anxiety"],
    rating: 4.2,
  },
  {
    id: "4",
    name: "Emily Brown",
    specialization: "Orthopedic Surgeon",
    experience: "12 years",
    issues: ["Back Pain", "Arthritis"],
    rating: 4.7,
  },
  {
    id: "5",
    name: "David Wilson",
    specialization: "Pediatrician",
    experience: "7 years",
    issues: ["Childhood Diseases", "Vaccinations"],
    rating: 4.3,
  },
  {
    id: "6",
    name: "Sarah Davis",
    specialization: "Dermatologist",
    experience: "9 years",
    issues: ["Skin Conditions", "Cosmetic Procedures"],
    rating: 4.6,
  },
  {
    id: "7",
    name: "Robert Taylor",
    specialization: "Neurologist",
    experience: "11 years",
    issues: ["Brain Disorders", "Nervous System Diseases"],
    rating: 4.4,
  },
  {
    id: "8",
    name: "Jennifer Anderson",
    specialization: "Gynecologist",
    experience: "10 years",
    issues: ["Women's Health", "Reproductive Issues"],
    rating: 4.5,
  },
  {
    id: "9",
    name: "Daniel Martinez",
    specialization: "Endocrinologist",
    experience: "13 years",
    issues: ["Diabetes", "Hormonal Disorders"],
    rating: 4.7,
  },
  {
    id: "10",
    name: "Laura Thompson",
    specialization: "Ophthalmologist",
    experience: "14 years",
    issues: ["Eye Disorders", "Vision Problems"],
    rating: 4.9,
  },
  {
    id: "11",
    name: "Christopher White",
    specialization: "Urologist",
    experience: "11 years",
    issues: ["Urinary Tract Disorders", "Male Reproductive Health"],
    rating: 4.6,
  },
  {
    id: "12",
    name: "Amanda Lee",
    specialization: "Dentist",
    experience: "10 years",
    issues: ["Oral Health", "Dental Procedures"],
    rating: 4.5,
  },
  {
    id: "13",
    name: "Brian Hall",
    specialization: "Allergist",
    experience: "9 years",
    issues: ["Allergies", "Immunology"],
    rating: 4.4,
  },
  {
    id: "14",
    name: "Samantha Clark",
    specialization: "Nutritionist",
    experience: "8 years",
    issues: ["Dietary Advice", "Nutritional Disorders"],
    rating: 4.3,
  },
  {
    id: "15",
    name: "Matthew King",
    specialization: "Physical Therapist",
    experience: "7 years",
    issues: ["Rehabilitation", "Musculoskeletal Disorders"],
    rating: 4.2,
  },
];
